### PR TITLE
Add support for creating mangas and covers

### LINKED ISSUE #55: Method to create Manga
There is currently no way to create a new manga.

### PR DESCRIPTION
**Pull request by PythonCoderAS**
Fix #55

### CODE REVIEW

**Comment by md-y** [comment]
This is absolutely fantastic.

Although, before I merge it, is there a reason for moving the manga constructor to ```_parse()```?

**Comment by PythonCoderAS** [comment]
> This is absolutely fantastic.
> 
> Although, before I merge it, is there a reason for moving the manga constructor to `_parse()`?

The reason I did that is that whenever I do an update, I need to re-parse the information that is sent. Obviously the version number has changed, but there's no sense in duplicating code, so I'd like to re-run the constructor. However, you can't call the constructor directly without making a new object, so I had to do this.

**Comment by md-y** [comment]
I cannot find any use of ```_parse``` outside of the constructor.

Screenshot

```update()``` is currently making a new object so is this meant to be there at all?

Wouldn't it also be possible to update the object by iterating over it with the new manga object kind of like this?
```javascript
let tempManga = new Manga(data)
Object.entries(tempManga).forEach(([k, v]) => {
    if (k in this) this[k] = v;
});
```
I don't know how optimal this solution is though.

**Comment by PythonCoderAS** [comment]
I think I changed my mind while writing this. I'll undo the constructor change.

**Comment by md-y** [comment]
I went ahead and reverted ```_parse``` and updated types so I can merge it

**Pull request merged**
